cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.jdk"
sudo: false
env:
  global:
  - TARGET=install
install: true
before_script:
- gpg --import ism.key
- if [ \( -n "${TRAVIS_TAG}" \) -a  "${TRAVIS_PULL_REQUEST}" = "false" ]; then export TARGET="deploy -P release"; fi;
script:
- ./jdk-wrapper.sh ./mvnw clean ${TARGET} --settings settings.xml -U -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
